### PR TITLE
fix(platform-redirect): Fixes the 500 error on /platform-redirect

### LINKED ISSUE #14244: Sentry redirection fails
### SDK

PHP SDK

### Description

Under Client Keys, your Sentry system says: "To send data to Sentry you will need to configure an SDK with a client key (usually referred to as the SENTRY_DSN value). For more information on integrating Sentry with your application take a look at our [documentation](https://docs.sentry.io/platform-redirect/?next=/configuration/options/)."

https://docs.sentry.io/platform-redirect/?next=/configuration/options/ is broken, 500 error.

### Suggested Solution

_No response_

### PR DESCRIPTION
**Pull request by BYK**
Fixes #14244

### CODE REVIEW

File: src/mdx.ts [hunk 1]
```diff
@@ -60,7 +60,9 @@ const root = process.cwd();
 const FILE_CONCURRENCY_LIMIT = 200;
 const CACHE_COMPRESS_LEVEL = 4;
 const CACHE_DIR = path.join(root, '.next', 'cache', 'mdx-bundler');
-mkdirSync(CACHE_DIR, {recursive: true});
+if (process.env.CI) {
+  mkdirSync(CACHE_DIR, {recursive: true});
```
Comment (BYK) [inline src/mdx.ts:64]: This should technically never throw a `ENOENT` but the internet is riddled with confused people encountering this. Guarding this to CI mode only too.

**Review by chargome — APPROVED** [review]

**Comment by BYK** [comment]
Confirmed that this works: https://sentry-docs-git-byk-fixenoent.sentry.dev/platform-redirect/?next=/configuration/environments/
