### PR TITLE
fix: Fix code block hydration errors

### LINKED ISSUE #10574: Hydration errors on dev server
### Steps to Reproduce

- Start local dev server according to instructions
- Navigate to any /platforms route
- Refresh

### Expected Result

Should refresh without hydration errors.

### Actual Result

Screenshot 2024-07-03 at 11 37 28

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by chargome**
- Remove unused code
- Stop using @next/mdx
- Load prismjs dynamically in `ApiExamples` component

fixes #10574 
might fix errors for switching code tabs (#10719)

### CODE REVIEW

File: src/mdxOptions.js
Comment (lforst) [inline src/mdxOptions.js:1]: Thanks for removing this. I think I missed this file in the changelog migration.

File: src/components/apiExamples/apiExamples.tsx [hunk 1]
```diff
@@ -25,29 +29,39 @@ function Example({api, selectedTabView, selectedResponse}: ExampleProps) {
...
+          className={jsonCodeBlockStyles}
           dangerouslySetInnerHTML={{
-            __html: Prism.highlight(
-              JSON.stringify(api.responses[selectedResponse].content?.schema, null, 2),
-              Prism.languages.json,
-              'json'
+            __html: JSON.stringify(
+              api.responses[selectedResponse].content?.schema,
+              null,
+              2
```
Comment (lforst) [inline src/components/apiExamples/apiExamples.tsx:64]: Is there any way uncontrolled input can land here?

File: src/components/apiExamples/apiExamples.tsx [hunk 2]
```diff
@@ -25,29 +29,39 @@ function Example({api, selectedTabView, selectedResponse}: ExampleProps) {
     exampleJson = api.responses[selectedResponse].content?.example;
   }
 
+  // load prism dynamically for these codeblocks,
+  // otherwise the highlighting applies globally
+  useEffect(() => {
```
Comment (lforst) [inline src/components/apiExamples/apiExamples.tsx:34]: Will this cause layout shift or flashing because it paints some time after the initial page load? 🤔

File: next.config.js [hunk 3]
```diff
@@ -33,15 +31,7 @@ const nextConfig = {
   redirects,
 };
 
-const withMDX = createMDX({
```
Comment (lforst) [inline next.config.js:36]: I was always wondering why we had this... thanks for removing.

File: app/layout.tsx [hunk 4]
```diff
@@ -28,7 +28,7 @@ export const metadata: Metadata = {
 
 export default function RootLayout({children}: {children: React.ReactNode}) {
   return (
-    <html lang="en" suppressHydrationWarning>
```
Comment (lforst) [inline app/layout.tsx:31]: 😎

**Review by lforst — APPROVED** [review]
Generally, I wouldn't mind if we merged in this state. However, can we leave a few extra comments explaining wtf is going on with the lazy loading stuff?

File: src/components/apiExamples/apiExamples.tsx (hunk 1 above)
Comment (chargome) [reply src/components/apiExamples/apiExamples.tsx:64]: good point, but no, this is just the filtered response of our openAPI call

File: src/components/apiExamples/apiExamples.tsx (hunk 2 above)
Comment (chargome) [reply src/components/apiExamples/apiExamples.tsx:34]: Yes, but it did that before as well. We could also think about not dynamically loading prismjs at all and instead use what we already have (rehypePrismPlus). This would streamline the style of the API JSON examples with our other codeblocks. This would require more work though, we can do it in another pr if needed.

**Comment by lforst** [comment]
Feel free to merge!
