### PR TITLE
fix trycatch integration 404

### LINKED ISSUE #10377: 🔗 404 Error
### URL

https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/trycatch/

this page is indexed by google

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by a-hariti**
fixes #10377

### CODE REVIEW

**Review by stephanie-anderson — APPROVED** [review]

File: src/middleware.ts [hunk 1]
```diff
@@ -61,6 +61,10 @@ type Redirect = {
 };
 
 const REDIRECTS: Redirect[] = [
+  {
+    from: '/platforms/javascript/guides/react/configuration/integrations/trycatch/',
```
Comment (stephanie-anderson) [inline src/middleware.ts:65]: Is it only react? Or should we make this dynamic for all guides?

**Review by stephanie-anderson — APPROVED** [review]

File: src/middleware.ts (hunk 1 above)
Comment (a-hariti) [reply src/middleware.ts:65]: I think it makes sense to make it dynamic it applied to other guides before

**Review by vivianyentran — APPROVED** [review]

File: src/middleware.ts [hunk 2]
```diff
@@ -61,6 +61,10 @@ type Redirect = {
 };
 
 const REDIRECTS: Redirect[] = [
+  {
+    fro: '/platforms/javascript/guides/react/configuration/integrations/trycatch/',
```
Comment (lizokm) [inline src/middleware.ts:65]:
```suggestion
    from: '/platforms/javascript/guides/react/configuration/integrations/trycatch/',
```
