### PR TITLE
fix: smarter sidebar scrolling behavior

### LINKED ISSUE #10978: Auto-scroll to active element in nav sidebar
### Problem Statement

Today, when you click on an element in the nav sidebar that is below the fold, you get to the new page, but loose focus in the sidebar. This is a bit confusing/disorienting. See:

https://github.com/user-attachments/assets/c0507f33-190e-4119-9765-72933535492f

### Solution Brainstorm

We should either keep scroll position in the sidebar, or at least scroll down to the active element on pageload.

### PR DESCRIPTION
**Pull request by a-hariti**
The current behavior of the sidebar is is jarring when dealing with items below the fold

this PR makes it smarter and behave as expected

closes #10978

### CODE REVIEW

File: src/components/focus-active-link.tsx [hunk 1]
```diff
@@ -1,23 +1,54 @@
...
+  useEffect(() => {
+    const sidebar = document.querySelector('[data-sidebar-link]')?.closest('aside');
+    if (!sidebar) {
+      return;
+    }
+    sidebar.addEventListener('click', e => {
+      const target = e.target as HTMLElement;
+      if (target.hasAttribute('data-sidebar-link')) {
+        const top = target.getBoundingClientRect().top;
+        sessionStorage.setItem('sidebar-link-poisition', top.toString());
```
Comment (chargome) [inline src/components/focus-active-link.tsx:21]: can we use local storage here? Session storage has been causing gdpr problems lately

File: src/components/focus-active-link.tsx [hunk 2]
```diff
@@ -1,23 +1,54 @@
...
-  const isVsibible = (link: Element) => {
-    const rect = link.getBoundingClientRect();
-    return rect.top >= 0 && rect.bottom <= window.innerHeight;
-  };
+  useEffect(() => {
+    const sidebar = document.querySelector('[data-sidebar-link]')?.closest('aside');
+    if (!sidebar) {
+      return;
+    }
+    sidebar.addEventListener('click', e => {
```
Comment (chargome) [inline src/components/focus-active-link.tsx:17]: Please remove all event listeners in the useEffect cleanup function!

**Review by chargome — CHANGES_REQUESTED** [review]
Thanks for adding this, works great! Left some feedback comments

File: src/components/focus-active-link.tsx (hunk 1 above)
Comment (a-hariti) [reply src/components/focus-active-link.tsx:21]: I think it's the perfect level of memory for this task (remember the position of the active link as long as the user is on the website)

why is it causing GDPR problems?

Comment (chargome) [reply src/components/focus-active-link.tsx:22]: Our problem was related to the usage of session storage using our SDKs. But I agree with you, let me just get that confirmed.

Comment (chargome) [reply src/components/focus-active-link.tsx:22]: good to go!

**Review by chargome — APPROVED** [review]
🚀
